markdown: rdiscount
permalink: /:title/
url: http://geek4it.com
name: GEEK4IT SEEKING WISDOM
author: GEEK4IT
twitter: Geek4IT
email: chunjianye@gmail.com
duoshuo: Geek4IT
github: Geek4IT
pygments: true
safe: true
paginate: 20
