markdown: kramdown
permalink: /:title/
url: http://geek4it.com
name: GEEK4IT
author: GEEK4IT
twitter: Geek4IT
email: chunjianye@gmail.com
github: Geek4IT
highlighter: rouge
pygments: true
safe: true
paginate: 20
