markdown: rdiscount
permalink: /:title/
url: http://geek4it.com
name: GEEK4IT
author: GEEK4IT
qq: 2670628125
email: chunjianye@gmail.com
duoshuo: yonsm
beian: 浙ICP备12026616号
weibo: 2670628125
github: Geek4IT
pygments: true
safe: true
paginate: 20
